basePath: /api/v1
host: localhost:8081
info:
  contact:
    email: nhat.ntm@teko.vn
    name: MINH NHAT TEAM WMS
    url: https://github.com/Nguyen-Nhat/teko-project-1
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/Nguyen-Nhat/teko-project-1
  title: API Documentation Student Service Backend
  version: "1.0"
paths: {}
swagger: "2.0"
