server:
  port: 8080
  mode: "dev"
  max_request_body: 10485760 #byte

logger:
  log_level: debug
  file_log_name: ./storage/log/dev.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

database:
  host: 127.0.0.1
  port: 5432
  username: root
  password: root
  dbname: library

cors:
  mode: all # all, whitelist
  white_list:
    - allow_origin: test1.com
      allow_headers: "*"
      allow_methods: GET, OPTIONS, POST, PUT, DELETE
      expose_headers: "*"
      allow_credentials: true

    - allow_origin: test2.com
      allow_headers: "*"
      allow_methods: GET, OPTIONS, POST, PUT, DELETE
      expose_headers: "*"
      allow_credentials: true
