// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"student/internal/controller"
	"student/internal/repository"
	"student/internal/service"
)

// Injectors from student.wire.go:

func InitStudentRouterHandler() *controller.StudentController {
	iStudentRepository := repository.NewStudentRepository()
	iUniversityRepository := repository.NewUniversityRepository()
	iStudentService := service.NewStudentService(iStudentRepository, iUniversityRepository)
	studentController := controller.NewStudentController(iStudentService)
	return studentController
}

// Injectors from university.wire.go:

func InitUniversityRouterHandler() *controller.UniversityController {
	iUniversityRepository := repository.NewUniversityRepository()
	iUniversityService := service.NewUniversityService(iUniversityRepository)
	universityController := controller.NewUniversityController(iUniversityService)
	return universityController
}
