// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "student/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// IUniversityRepository is an autogenerated mock type for the IUniversityRepository type
type IUniversityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, university
func (_m *IUniversityRepository) Create(ctx context.Context, university *model.University) error {
	ret := _m.Called(ctx, university)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.University) error); ok {
		r0 = rf(ctx, university)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *IUniversityRepository) FindByID(ctx context.Context, id int) (*model.University, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.University
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.University, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.University); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.University)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUniversityRepository creates a new instance of IUniversityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUniversityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUniversityRepository {
	mock := &IUniversityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
